### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './base_data/mel_stats.npy'

### ISSUE THREAD

**Issue by carlosedubarreto** [winddori2002/TriAAN-VC#1]
I was testing the code and got this error
`FileNotFoundError: [Errno 2] No such file or directory: './base_data/mel_stats.npy'`

I have searched for this file but could not find it.
Can you point me a direction to solve this?

I was traing to execute the converter using the pre trained models, I didnt train.

Thanks

**Comment by winddori2002** [comment]
Hi
I have updated mel_stats.npy in the base_data directory.
You can also test after making meta data for VCTK dataset.
Thank you

**Comment by carlosedubarreto** [comment]
Working great. Thanks
