### ISSUE TITLE
Training Logs

### ISSUE THREAD

**Issue by Shmuel-Gruel** [winddori2002/TriAAN-VC#11]
Hello! 
Do you have any graphs or logs from your training?
I wanted to check if my loss curve is reasonable.
Thank you.

**Comment by winddori2002** [comment]
Hi,

You can check these log files.

The dataset split can be different, but it will be helpful to understand the loss curve trend.

Train loss log.
![logs_train loss](https://github.com/winddori2002/TriAAN-VC/assets/49035579/200ac99c-c44a-4522-a0f0-21b890511fce)

Valid loss log.
![logs_valid loss](https://github.com/winddori2002/TriAAN-VC/assets/49035579/416eeb7b-6f4d-43d6-b7bd-adc7e969e73e)

Thanks.

**Comment by Shmuel-Gruel** [comment]
Great, thank you a lot.
