### ISSUE TITLE
Mixed datasets and calculate the threshold value

### ISSUE THREAD

**Issue by brian-gyh** [winddori2002/TriAAN-VC#12]
What may happen if I mix VCTK datasets with datasets from other languages? For example, I used a dataset mixed with VCTK and Chinese. How should I calculate the threshold value of test in "config/base.yaml" at this time?

**Comment by winddori2002** [comment]
Hi,

In that case, it will be better to recalculate the threshold. #9 
However, the voice encoder (speaker verification) is not trained on the Chinese dataset, I guess it may not work well.

Thanks.

**Comment by brian-gyh** [comment]
Ok, thanks for your reply. 

So do I need to retrain the CPC and Vocoder Parallel WaveGAN parts?

**Comment by winddori2002** [comment]
Yes. 
Different language datasets will affect the model performance a lot.
