### ISSUE TITLE
Training time/compute for provided model

### ISSUE THREAD

**Issue by nateraw** [winddori2002/TriAAN-VC#3]
Hi there, thanks for sharing this codebase and the associated models :) 

Was curious about a couple things:

1. how long did it take to train on the VCTK dataset, and
2. What compute was used? (Type+number of gpus)

This info might help folks who want to look into training on a larger dataset. I tried finding this info in the paper/here but didn't find anything (sorry if I missed something!) Thanks!

**Comment by winddori2002** [comment]
Hi, 

We used a single RTX3090 GPU, and it took about 45 hours for training TriAAN-VC on the VCTK dataset (with the paper training setting, batch size: 32, epoch: 500).

Thank you.

**Comment by nateraw** [comment]
Thank you!! :)

**Comment by brian-gyh** [comment]
> Hi,
> 
> We used a single RTX3090 GPU, and it took about 45 hours for training TriAAN-VC on the VCTK dataset (with the paper training setting, batch size: 32, epoch: 500).
> 
> Thank you.

Hi,

The training settings in your paper are not batch_ Size=64, epochs=400?

![image](https://github.com/winddori2002/TriAAN-VC/assets/104077097/4cfb884f-23d0-491d-b671-35ae0b56be04)
